#-------------------------------
# General Site Settings

title: Graven Riddles | Valuable Indie Game Studio
description: We aim to enrich your experience and wisdom by creating unique action adventure games. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Graven Riddles
author-avatar: 


#-------------------------------
# Contact links
youtube: http://bit.ly/2ZkU77t
twitch: http://bit.ly/2L9rK2L
facebook: http://bit.ly/2U6Bqit
twitter: http://bit.ly/2ZuiXBG
instagram: http://bit.ly/2U9duev


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-www-gravenriddles-com # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-146420314-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: https://twitter.us20.list-manage.com/subscribe/post?u=a2c3523d0a8e51b97f6a6b82c&amp;id=c68f537ff3 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
